### ISSUE TITLE
could you please show how to add a cat to the list

### ISSUE THREAD

**Issue by pabl0rg** [charpeni/svelte-example#1]
using a text input

thanks

**Comment by proyb6** [comment]
You can simply include appendchild under ```method:```, using vanilla javascript is fine.
http://www.w3schools.com/jsref/met_node_appendchild.asp

**Comment by guinetn** [comment]
Add a new cat: see catlist.html and catlist.js in
https://github.com/guinetn/svelte-example

**Comment by proyb6** [comment]
If the user is in trusted account or environment, will we use unsafe triple bracket ```{{{}}}``` if the user need to extend HTML elements like h4, p, etc?

**Comment by charpeni** [comment]
Merged in #4.
