### ISSUE TITLE
IE11: javascript in components not compiled by babel

### ISSUE THREAD

**Issue by dschulten** [charpeni/svelte-example#8]
In the current rollup.config.js the javascript code compiled by svelte is not transpiled with babel, therefore you get:

var template = (function () {
  return {
    data () {
      return {}
    },
  };
}());

which fails in IE 11. Please change the rollup configuration so that babel not only compiles src/js, but also the svelte output.

**Comment by antony** [comment]
I've got the same problem in my production code - I was hoping this project would show me how to fix it.

Seems like there might be a problem somewhere in the rollup/babel/svelte stack.

**Comment by Rich-Harris** [comment]
Came here via https://github.com/sveltejs/svelte/issues/717 — it's essential that the Babel plugin comes *after* the Svelte plugin, not before it, so that it can transpile the generated JavaScript (it won't transpile code inside a `<script>` tag).
