### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by realulim** [charpeni/svelte-example#9]
I cloned the git repo and then ran npm install and npm run build, this error appeared:

Cannot read property 'Symbol(Symbol.iterator)' of undefined

node 7.10.1
npm 4.2.0

**Comment by charpeni** [comment]
Can you try with yarn instead of npm? https://yarnpkg.com

**Comment by realulim** [comment]
Yup, it builds with yarn.

**Comment by charpeni** [comment]
Thanks.

You can stick with yarn until I update the dependencies version in package.json.
